[2022-08-11 23:24:34,362] {_internal.py:113} MainThread INFO in _internal:  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
[2022-08-11 23:25:32,009] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:28:00,260] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:28:06,023] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/login [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 19, in login
    response = user_service.login(data)
TypeError: login() missing 1 required positional argument: 'login_req'
[2022-08-11 23:28:06,031] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:28:06] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 500 -
[2022-08-11 23:33:23,400] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:34:01,428] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:34:01] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-11 23:49:22,614] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:49:22] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-11 23:49:24,642] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:49:31,438] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 99, in add_headers
    "userId": api_request.headers["x-user-id"],
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2022-08-11 23:49:31,449] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:49:31] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-11 23:50:24,050] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:50:24] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:50:43,711] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:50:43] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:51:47,569] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:51:47] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:52:33,402] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:52:36,855] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:52:36] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:52:57,740] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:53:00,407] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:53:00] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:53:51,057] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:53:53,562] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:53:53] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:54:59,460] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:55:02,447] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:55:02] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:55:19,818] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:55:23,139] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:55:23] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:56:13,512] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:56:13] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:56:24,339] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:56:57,385] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:56:57] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-11 23:58:43,680] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:58:45,744] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:58:45] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-11 23:59:08,441] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-11 23:59:10,620] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 106, in add_headers
    if api_headers["x-key"] == x_key:
KeyError: 'x-key'
[2022-08-11 23:59:10,626] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [11/Aug/2022 23:59:10] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-12 00:00:33,730] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 11:47:54,093] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:15:43,774] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:16:29,096] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:16:29] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:18:09,820] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:18:17,749] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:18:17] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:19:06,787] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:19:12,012] {userservice.py:33} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:19:12,270] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:19:12] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:29:17,262] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:29:26,749] {userservice.py:22} Thread-1 INFO in userservice: Signing Up...
[2022-08-12 12:29:26,764] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:29:26] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 400 -
[2022-08-12 12:30:35,037] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:30:39,561] {userservice.py:22} Thread-1 INFO in userservice: Signing Up...
[2022-08-12 12:30:39,568] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:30:39] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:32:04,788] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:04] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 400 -
[2022-08-12 12:32:27,601] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:27] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 400 -
[2022-08-12 12:32:44,688] {userservice.py:75} Thread-4 INFO in userservice: Session Expired
[2022-08-12 12:32:44,688] {_internal.py:113} Thread-4 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:32:44] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 403 -
[2022-08-12 12:33:02,675] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:33:06,741] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:33:06,750] {userservice.py:57} Thread-1 INFO in userservice: {'email': 'vishal.mahuli@tarento.com', 'password': b'$2b$12$8SlPGiE0PsL9XHgMme2oqOgczi/CxO.EOTw0uViZDfoaonbCra/ki', 'username': 'vishal.mahuli@tarento.com', 'userId': '98746fd1-e9e0-4050-9f44-effc1cd3a25a'}
[2022-08-12 12:33:07,066] {userservice.py:59} Thread-1 INFO in userservice: b'$2b$12$i9yLSw0MYRIc2.9AIufC5.eCyFTJ3u6efaDJXnyi7FgBIsFrfx83C'
[2022-08-12 12:33:07,067] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:33:07] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:33:55,225] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:34:01,365] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:34:01,370] {userservice.py:57} Thread-1 INFO in userservice: {'email': 'vishal.mahuli@tarento.com', 'password': b'$2b$12$8SlPGiE0PsL9XHgMme2oqOgczi/CxO.EOTw0uViZDfoaonbCra/ki', 'username': 'vishal.mahuli@tarento.com', 'userId': '98746fd1-e9e0-4050-9f44-effc1cd3a25a'}
[2022-08-12 12:34:01,624] {userservice.py:59} Thread-1 INFO in userservice: b'$2b$12$yYri9u5wh7iBQrw5XvdOwebLSPc3SzyJ1t1l/hkzm/BUkWx6bhXVG'
[2022-08-12 12:34:01,625] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:34:01] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:41:49,374] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:41:57,689] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:41:57,712] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:41:57] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:42:32,551] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:42:37,964] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:42:37,991] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:42:37] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:51:14,873] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:51:23,147] {userservice.py:52} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:51:23,651] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:51:23] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:51:39,493] {app.py:1891} Thread-2 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/signup [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 51, in signup
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 122, in add_headers
    "userId": api_request.headers["x-user-id"],
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1463, in __getitem__
    return _unicodify_header_value(self.environ["HTTP_" + key])
KeyError: 'HTTP_X_USER_ID'
[2022-08-12 12:51:39,504] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:51:39] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 500 -
[2022-08-12 12:54:09,831] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:54:17,505] {userservice.py:41} Thread-1 INFO in userservice: Deleting User...
[2022-08-12 12:54:17,512] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:17] "[37mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 200 -
[2022-08-12 12:54:34,654] {userservice.py:24} Thread-2 INFO in userservice: Signing Up...
[2022-08-12 12:54:34,910] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:34] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 12:54:43,417] {userservice.py:52} Thread-3 INFO in userservice: Logging in...
[2022-08-12 12:54:43,887] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:54:43] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:55:55,399] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:56:02,353] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:56:02,357] {ddsutils.py:27} Thread-1 INFO in ddsutils: pwd: b'$2b$12$E1bvtT7C2cJZvl6rSxlwseM4iGE/hON2fCSQAO9wVP7NUZbGsne6e' | ip_pwd: 123456
[2022-08-12 12:56:02,861] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:56:02] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 12:57:32,077] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 12:57:35,981] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 12:57:36,241] {ddsutils.py:24} Thread-1 INFO in ddsutils: pwd: b'$2b$12$E1bvtT7C2cJZvl6rSxlwseM4iGE/hON2fCSQAO9wVP7NUZbGsne6e' | ip_pwd: b'$2b$12$DDT4ajThARjVh1JUtqZNoeoZAotc3iti2tdiH4zC6GrA3eF360Wxe'
[2022-08-12 12:57:36,492] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 12:57:36] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:01:58,445] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:02:05,379] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 13:02:05,402] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:02:05] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:04:47,818] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:04:54,682] {userservice.py:50} Thread-1 INFO in userservice: Logging in...
[2022-08-12 13:04:54,743] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:04:54] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 400 -
[2022-08-12 13:13:32,061] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 13:13:40,823] {userservice.py:39} Thread-1 INFO in userservice: Deleting User...
[2022-08-12 13:13:40,831] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:40] "[37mPOST /dmu-datastore/data-upload-service/v1/users/delete HTTP/1.1[0m" 200 -
[2022-08-12 13:13:43,730] {userservice.py:22} Thread-2 INFO in userservice: Signing Up...
[2022-08-12 13:13:43,975] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:43] "[37mPOST /dmu-datastore/data-upload-service/v1/signup HTTP/1.1[0m" 200 -
[2022-08-12 13:13:50,813] {userservice.py:50} Thread-3 INFO in userservice: Logging in...
[2022-08-12 13:13:51,068] {ddsutils.py:25} Thread-3 INFO in ddsutils: b'$2b$12$KMBd.ohO3GL7UTu92UejJeStJGkz0rqSrYvpk0hTlvM193xZQ7UWe'
[2022-08-12 13:13:51,068] {ddsutils.py:26} Thread-3 INFO in ddsutils: b'$2b$12$KMBd.ohO3GL7UTu92UejJeStJGkz0rqSrYvpk0hTlvM193xZQ7UWe'
[2022-08-12 13:13:51,162] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 13:13:51] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 14:10:01,076] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:10:07,131] {app.py:1891} Thread-1 ERROR in app: Exception on /dmu-datastore/data-upload-service/v1/document/upload [POST]
Traceback (most recent call last):
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vishalmahuli/Desktop/dmu-datastore/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 82, in doc_upload
    data = add_headers(data, request)
  File "/Users/vishalmahuli/Desktop/dmu-datastore/controller/ddscontroller.py", line 131, in add_headers
    data["metadata"] = headers
TypeError: 'NoneType' object does not support item assignment
[2022-08-12 14:10:07,138] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:10:07] "[35m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 500 -
[2022-08-12 14:10:45,118] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:11:34,636] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:11:38,853] {userservice.py:78} Thread-1 INFO in userservice: Session Expired
[2022-08-12 14:11:38,853] {userservice.py:84} Thread-1 INFO in userservice: Logging out...
[2022-08-12 14:11:38,863] {userservice.py:93} Thread-1 INFO in userservice: Logged out successfully!
[2022-08-12 14:11:38,863] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:11:38] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 403 -
[2022-08-12 14:11:51,228] {userservice.py:50} Thread-2 INFO in userservice: Logging in...
[2022-08-12 14:11:51,492] {_internal.py:113} Thread-2 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:11:51] "[37mPOST /dmu-datastore/data-upload-service/v1/login HTTP/1.1[0m" 200 -
[2022-08-12 14:12:12,999] {ddsservice.py:27} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Uploading file...
[2022-08-12 14:12:12,999] {ddsservice.py:46} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Parsing metadata file...
[2022-08-12 14:12:13,457] {ddsservice.py:50} Thread-3 INFO in ddsservice: Metadata Filename: test-metadata.csv, MIME Type: text/csv
[2022-08-12 14:12:13,491] {ddsservice.py:30} Thread-3 INFO in ddsservice: 6581403a-ed15-4269-8a9c-18f099011b60 | Metadata file couldn't be parsed!
[2022-08-12 14:12:13,493] {_internal.py:113} Thread-3 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:12:13] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 400 -
[2022-08-12 14:14:18,575] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
[2022-08-12 14:14:25,185] {ddsservice.py:27} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Uploading file...
[2022-08-12 14:14:25,185] {ddsservice.py:46} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Parsing metadata file...
[2022-08-12 14:14:25,701] {ddsservice.py:50} Thread-1 INFO in ddsservice: Metadata Filename: test-metadata.csv, MIME Type: text/csv
[2022-08-12 14:14:25,738] {ddsservice.py:30} Thread-1 INFO in ddsservice: 1600b421-8f26-46d1-a762-1d1db70e7db4 | Metadata file couldn't be parsed!
[2022-08-12 14:14:25,743] {_internal.py:113} Thread-1 INFO in _internal: 127.0.0.1 - - [12/Aug/2022 14:14:25] "[31m[1mPOST /dmu-datastore/data-upload-service/v1/document/upload HTTP/1.1[0m" 400 -
[2022-08-12 14:19:02,836] {_internal.py:113} MainThread INFO in _internal:  * Running on http://localhost:5001/ (Press CTRL+C to quit)
